#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VTop.h"  // This header is generated by Chisel

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    
    // Initialize Verilator traces
    Verilated::traceEverOn(true);
    VerilatedVcdC* tfp = new VerilatedVcdC;

    // Create an instance of the generated Verilog module
    VTop* top = new VTop;

    // Trace the signals
    top->trace(tfp, 99);
    tfp->open("dump1.vcd");

    // Initialize signals
    top->reset = 1;

    // for (int i = 0; i < 32; i++) {
    //     switch(i) {
               top->io_Stationary_matrix_0_0 = 0;
              top->io_Stationary_matrix_0_1 = 0; 
            //  top->io_Stationary_matrix_0_2 = 13; 
            //    top->io_Stationary_matrix_0_3 = 14; 
               top->io_Stationary_matrix_1_0 = 1; 
               top->io_Stationary_matrix_1_1 = 1; 
            //    top->io_Stationary_matrix_2_2 = 9; 
            //    top->io_Stationary_matrix_2_3 = 10; 
            //    top->io_Stationary_matrix_3_0 = 21; 
            //    top->io_Stationary_matrix_3_1 = 23; 
            //    top->io_Stationary_matrix_3_2 = 24;
            //   top->io_Stationary_matrix_3_3 = 25;
        
    
    // for (int i = 0; i < 32; i++) {
    //     switch(i) {
            top->io_Streaming_matrix_0_0 = 1;
            top->io_Streaming_matrix_0_1 = 3;
            // top->io_Streaming_matrix_0_2 = 7;
            // top->io_Streaming_matrix_0_3 = 0;
            top->io_Streaming_matrix_1_0 = 2;
            top->io_Streaming_matrix_1_1 = 1;
            // top->io_Streaming_matrix_1_2 = 10;
            //  top->io_Streaming_matrix_1_3 = 0;
            // top->io_Streaming_matrix_2_0 = 6;
            //  top->io_Streaming_matrix_2_1 = 3;
            // top->io_Streaming_matrix_2_2 = 0;
            // top->io_Streaming_matrix_2_3 = 0;
            //  top->io_Streaming_matrix_3_0 = 7;
            //  top->io_Streaming_matrix_3_1 = 1;
            //  top->io_Streaming_matrix_3_2 = 0;
            //  top->io_Streaming_matrix_3_3 = 0;
        
    //}
    // Simulation steps
    for (int cycle = 0; cycle < 2000; cycle++) {
        // Toggle clock
        top->clock = 1;
        top->eval();
        tfp->dump(cycle * 10 + 5);

        top->clock = 0;
        top->eval();
        tfp->dump(cycle * 10 + 10);

        if (cycle >= 2){
            top-> reset = 0;
        }
    }

    // ...


    // Close VCD
    tfp->close();
    delete top;
    return 0;
}